// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.2
// source: greetpb_ticket/greet.proto

package greetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Greeting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UId   int64  `protobuf:"varint,3,opt,name=u_id,json=uId,proto3" json:"u_id,omitempty"`
	Time  string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Price int64  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Greeting) Reset() {
	*x = Greeting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greetpb_ticket_greet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeting) ProtoMessage() {}

func (x *Greeting) ProtoReflect() protoreflect.Message {
	mi := &file_greetpb_ticket_greet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeting.ProtoReflect.Descriptor instead.
func (*Greeting) Descriptor() ([]byte, []int) {
	return file_greetpb_ticket_greet_proto_rawDescGZIP(), []int{0}
}

func (x *Greeting) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Greeting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Greeting) GetUId() int64 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *Greeting) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Greeting) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GreetRequestInsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *GreetRequestInsert) Reset() {
	*x = GreetRequestInsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greetpb_ticket_greet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetRequestInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequestInsert) ProtoMessage() {}

func (x *GreetRequestInsert) ProtoReflect() protoreflect.Message {
	mi := &file_greetpb_ticket_greet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequestInsert.ProtoReflect.Descriptor instead.
func (*GreetRequestInsert) Descriptor() ([]byte, []int) {
	return file_greetpb_ticket_greet_proto_rawDescGZIP(), []int{1}
}

func (x *GreetRequestInsert) GetGreeting() *Greeting {
	if x != nil {
		return x.Greeting
	}
	return nil
}

type GreetResponseInsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err    string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GreetResponseInsert) Reset() {
	*x = GreetResponseInsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greetpb_ticket_greet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetResponseInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponseInsert) ProtoMessage() {}

func (x *GreetResponseInsert) ProtoReflect() protoreflect.Message {
	mi := &file_greetpb_ticket_greet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponseInsert.ProtoReflect.Descriptor instead.
func (*GreetResponseInsert) Descriptor() ([]byte, []int) {
	return file_greetpb_ticket_greet_proto_rawDescGZIP(), []int{2}
}

func (x *GreetResponseInsert) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *GreetResponseInsert) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type GreetRequestLatest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GreetRequestLatest) Reset() {
	*x = GreetRequestLatest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greetpb_ticket_greet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetRequestLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequestLatest) ProtoMessage() {}

func (x *GreetRequestLatest) ProtoReflect() protoreflect.Message {
	mi := &file_greetpb_ticket_greet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequestLatest.ProtoReflect.Descriptor instead.
func (*GreetRequestLatest) Descriptor() ([]byte, []int) {
	return file_greetpb_ticket_greet_proto_rawDescGZIP(), []int{3}
}

func (x *GreetRequestLatest) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GreetResponseLatest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *GreetResponseLatest) Reset() {
	*x = GreetResponseLatest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greetpb_ticket_greet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetResponseLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponseLatest) ProtoMessage() {}

func (x *GreetResponseLatest) ProtoReflect() protoreflect.Message {
	mi := &file_greetpb_ticket_greet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponseLatest.ProtoReflect.Descriptor instead.
func (*GreetResponseLatest) Descriptor() ([]byte, []int) {
	return file_greetpb_ticket_greet_proto_rawDescGZIP(), []int{4}
}

func (x *GreetResponseLatest) GetGreeting() *Greeting {
	if x != nil {
		return x.Greeting
	}
	return nil
}

var File_greetpb_ticket_greet_proto protoreflect.FileDescriptor

var file_greetpb_ticket_greet_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x22, 0x6b, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x11, 0x0a, 0x04, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x41, 0x0a, 0x12, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x22, 0x3f, 0x0a, 0x13, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x42, 0x0a, 0x13, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x32, 0xa0, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x0b, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x19,
	0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x5c, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x3b, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greetpb_ticket_greet_proto_rawDescOnce sync.Once
	file_greetpb_ticket_greet_proto_rawDescData = file_greetpb_ticket_greet_proto_rawDesc
)

func file_greetpb_ticket_greet_proto_rawDescGZIP() []byte {
	file_greetpb_ticket_greet_proto_rawDescOnce.Do(func() {
		file_greetpb_ticket_greet_proto_rawDescData = protoimpl.X.CompressGZIP(file_greetpb_ticket_greet_proto_rawDescData)
	})
	return file_greetpb_ticket_greet_proto_rawDescData
}

var file_greetpb_ticket_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_greetpb_ticket_greet_proto_goTypes = []interface{}{
	(*Greeting)(nil),            // 0: greet.Greeting
	(*GreetRequestInsert)(nil),  // 1: greet.GreetRequestInsert
	(*GreetResponseInsert)(nil), // 2: greet.GreetResponseInsert
	(*GreetRequestLatest)(nil),  // 3: greet.GreetRequestLatest
	(*GreetResponseLatest)(nil), // 4: greet.GreetResponseLatest
}
var file_greetpb_ticket_greet_proto_depIdxs = []int32{
	0, // 0: greet.GreetRequestInsert.greeting:type_name -> greet.Greeting
	0, // 1: greet.GreetResponseLatest.greeting:type_name -> greet.Greeting
	1, // 2: greet.GreetService.InsertGreet:input_type -> greet.GreetRequestInsert
	3, // 3: greet.GreetService.LatestGreet:input_type -> greet.GreetRequestLatest
	2, // 4: greet.GreetService.InsertGreet:output_type -> greet.GreetResponseInsert
	4, // 5: greet.GreetService.LatestGreet:output_type -> greet.GreetResponseLatest
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_greetpb_ticket_greet_proto_init() }
func file_greetpb_ticket_greet_proto_init() {
	if File_greetpb_ticket_greet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greetpb_ticket_greet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greeting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greetpb_ticket_greet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetRequestInsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greetpb_ticket_greet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetResponseInsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greetpb_ticket_greet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetRequestLatest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greetpb_ticket_greet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetResponseLatest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greetpb_ticket_greet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greetpb_ticket_greet_proto_goTypes,
		DependencyIndexes: file_greetpb_ticket_greet_proto_depIdxs,
		MessageInfos:      file_greetpb_ticket_greet_proto_msgTypes,
	}.Build()
	File_greetpb_ticket_greet_proto = out.File
	file_greetpb_ticket_greet_proto_rawDesc = nil
	file_greetpb_ticket_greet_proto_goTypes = nil
	file_greetpb_ticket_greet_proto_depIdxs = nil
}
